apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  namespace: traincloud-dev
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      serviceAccountName: email-serviceaccount
      automountServiceAccountToken: false
      nodeSelector:
        deployment_node: traincloud-dev-microservices # Label in IONOS k8s node pool
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: email
          image: traincloud.cr.de-fra.ionos.com/microservices/email:v0.0.20
          ports:
            - containerPort: 10103
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #     ephemeral-storage: "256Mi"
          #   limits:
          #     memory: "256Mi"
          #     ephemeral-storage: "512Mi"
          env:
            - name: TRAINCLOUD_SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TRAINCLOUD_SERVICE_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ASPNETCORE_HTTP_PORTS
              value: "10103"
            - name: MESSAGEBUS_HOSTNAME
              value: "rabbitmq-service-queue.traincloud-dev.svc.cluster.local"
            - name: MESSAGEBUS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: messagebus_username
            - name: MESSAGEBUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: messagebus_password
            - name: JWT_ISSUERSIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: jwt_issuersigningkey
            - name: EMAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_server
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_username
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_password
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_port
      imagePullSecrets: 
        - name: traincloud-container-registry-credentials