apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  namespace: traincloud-net
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      serviceAccountName: email-serviceaccount
      automountServiceAccountToken: false
      nodeSelector:
        deployment_node: traincloud-net-microservices # Label in IONOS k8s node pool
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: email
          image: traincloud.cr.de-fra.ionos.com/microservices/email:v0.0.10
          ports:
            - containerPort: 10203
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "256Mi"
              ephemeral-storage: "512Mi"
          env:
            - name: TRAINCLOUD_SERVICE_ENVIRONMENT
              value: "traincloud-net"
            - name: ASPNETCORE_HTTP_PORTS
              value: "10203"
      imagePullSecrets: 
        - name: traincloud-container-registry-credentials
