name: Build and push to IONOS Container Registry

on:
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get the tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Log in to IONOS Container Registry
        uses: docker/login-action@v3
        with:
          registry:  ${{ secrets.IONOS_CONTAINER_REGISTRY_HOSTNAME }}
          username: ${{ secrets.IONOS_CONTAINER_REGISTRY_TOKENNAME }}
          password:  ${{ secrets.IONOS_CONTAINER_REGISTRY_TOKEN  }}

      - name: Build Docker image
        run: |          
          docker build -t "${{ secrets.IONOS_CONTAINER_REGISTRY_HOSTNAME }}/microservices/email:${{ steps.get_tag.outputs.TAG }}" --build-arg NuGetPackageSourceCredentials_TrainCloud="Username=${{ secrets.TRAINCLOUD_CHECKOUT_USER }};Password=${{ secrets.TRAINCLOUD_CHECKOUT_TOKEN }}" . 

      - name: Push Docker image
        run: |
          docker push "${{ secrets.IONOS_CONTAINER_REGISTRY_HOSTNAME }}/microservices/email:${{ steps.get_tag.outputs.TAG }}"
        